spring:
  application:
    name: wxshop-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml

wxshop:
  orderservice:
    version: 1.0.0
    url: ""
  redis:
    host: 127.0.0.1
    port: 6379
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181

