spring:
  application:
    name: wxshop-main
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml
wxshop:
  orderservice:
    version: 0.0.1
  redis:
    host: 127.0.0.1
    port: 6379
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8000

